"""
parse_all_resumes_to_json.py — HireFlow-Lite Resume JSON Exporter
===================================================================
Exports the exact JSON structure generated by HireFlow-Lite's resume parser
for all resumes stored in the database / uploads folder.

Usage:
    venv\\Scripts\\python.exe parse_all_resumes_to_json.py
"""

import sys
import json
from pathlib import Path

# Force UTF-8 on Windows
try:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass

from database import connect, get_all_students, get_student


def export_parsed_resumes():
    conn = connect()
    students_summary = get_all_students(conn)
    
    parsed_json_list = []
    
    print(f"=== Exporting Parsed JSON for {len(students_summary)} Resumes ===\n")
    
    for s in students_summary:
        roll = s["roll_number"]
        st = get_student(conn, roll)
        
        # Build exact parsed dictionary structure returned by resume_parser.parse_resume()
        parsed_data = {
            "roll_number": st.get("roll_number", ""),
            "name": st.get("name", ""),
            "email": st.get("email", ""),
            "github_username": st.get("github_url", "").replace("https://github.com/", "").replace("http://github.com/", "").replace("https://www.github.com/", "").rstrip("/"),
            "github_url": st.get("github_url", ""),
            "phone": st.get("phone", ""),
            "education": st.get("education", ""),
            "skills": st.get("skills", []),
            "projects": st.get("projects", []),
            "ats_score": st.get("ats_score", 0.0),
            "github_score": st.get("github_score"),
            "composite_score": st.get("composite_score", 0.0),
            "final_score": st.get("final_score", 0.0),
            "matched_skills": st.get("matched_skills", []),
            "missing_skills": st.get("missing_skills", []),
            "project_verifications": st.get("project_verif", []),
            "resume_filename": st.get("resume_filename", ""),
            "raw_text_snippet": st.get("raw_text", "")[:300] + ("..." if len(st.get("raw_text", "")) > 300 else ""),
        }
        
        parsed_json_list.append(parsed_data)
        
    conn.close()
    
    # Save to parsed_resumes.json
    output_path = Path(__file__).parent / "parsed_resumes.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(parsed_json_list, f, indent=2, ensure_ascii=False)
        
    print(f"[OK] Successfully saved parsed JSON for all {len(parsed_json_list)} resumes to:")
    print(f"     {output_path}\n")
    
    return parsed_json_list


if __name__ == "__main__":
    data = export_parsed_resumes()
    
    # Print formatted JSON output to stdout
    print("=" * 70)
    print("PARSED RESUMES JSON OUTPUT:")
    print("=" * 70)
    print(json.dumps(data, indent=2, ensure_ascii=False))
